modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Deftu/Textile/issues"
license="LGPL-3.0-or-later"

[[mods]]
    modId="testmod"
    version="1.0.0"
    displayName="Test Mod"
    description="A test mod for testing purposes."
    authors="Deftu"

[[dependencies.testmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
